version: '3'
services:
  api:
    container_name: api
    restart: always
    build: api
    ports:
      - 3000:3000
    volumes:
      - ./api:/usr/src/app
    depends_on: 
      - mongo
      - zookeeper
      - kafka
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
     - 2181:2181
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  mongodb:
  api: